name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Shuttle login
      run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}
    - name: Deploy
      run: cargo shuttle deploy
